######################################################################
# Automatically generated by qmake (3.1) Fri Jun 2 15:48:01 2017
######################################################################

TEMPLATE = app
TARGET = project
INCLUDEPATH += .
QT += widgets
QT += charts
QT += serialport
QT += core

# Input
HEADERS += data.h Window.h
SOURCES += data.cpp main.cpp Window.cpp
