# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('T1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T6', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T7', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T8', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
