# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temper',
            new_name='temp',
        ),
    ]
