# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temper', '0003_auto_20171022_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temper',
            name='T1',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='temper',
            name='T2',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='temper',
            name='T3',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='temper',
            name='T4',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='temper',
            name='T5',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='temper',
            name='T6',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='temper',
            name='T7',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='temper',
            name='T8',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
